### ISSUE TITLE
Add more helper methods

### ISSUE THREAD

**Issue by StyleT** [davidkalosi/js-money#19]
Hi! Looks like this library lacks the following methods:

- greaterThan
- greaterThanOrEqual
- lessThan
- lessThanOrEqual
- getAmount
- getCurrency

It will significantly improve readability of code that was written with the usage of this library.

**Comment by StyleT** [comment]
@davidkalosi I can do a PR for this in 1-2 days. Is it ok for you? I just want to understand the best solution for my company: support this library or create a fork.

**Comment by davidkalosi** [comment]
Hi,

Please go ahaead with the PR I am happy to merge it ;)

**Comment by davidkalosi** [comment]
merged. thank you for your contribution.

**Comment by StyleT** [comment]
@davidkalosi Hi! Can you please publish new version of package to NPM with this changes?

**Comment by davidkalosi** [comment]
@StyleT published version 0.6.0
