### ISSUE TITLE
Bitcoin currency?

### ISSUE THREAD

**Issue by jomendoz** [davidkalosi/js-money#26]
Is there a reason why BTC hasn't been added to currencies.js? If there is no problem, I'd do a PR with this:

`    "BTC": {
        "symbol": "BTC",
        "name": "Bitcoin",
        "symbol_native": "B͈̎",
        "decimal_digits": 8,
        "rounding": 0,
        "code": "XBT",
        "name_plural": "Bitcoins"
    },`

**Comment by davidkalosi** [comment]
Go ahead ;)

**Comment by jomendoz** [comment]
Changes are ready in #27

**Comment by davidkalosi** [comment]
Version 0.6.3 published on npmjs.
