### ISSUE TITLE
Why not always add decimals?

### ISSUE THREAD

**Issue by Snorlock** [davidkalosi/js-money#4]
Is there a reason you have decided to not always append decimals to the amount? It might seem confusing when you make money out of 1000 you get 1000, but when you make money out of 1000.00 you get 100000.
Should it not be consistent?

**Comment by davidkalosi** [comment]
this is the correct behavior - when you pass an integer this is the same as the internal representation so it is just passed on. the double precision argument is just a convenience parsing function and it gets converted to the required integer based on the decimal places allowed by the currency.

it's just a way of using the same constructor in the backed where money amounts are fetched from the database (integers) and from the GUI where the users usually enter 10.xy

**Comment by Snorlock** [comment]
Yeah I agree, but we experienced an issue now that if you allow either or, you can get missrepresented values in the library. I suggest that you rather dismiss decimal handling and focus on minimum value currency. That is what we have done now around your library.

But since you have this simple decimal handling in the constructor, money can easily become multiplied by accident. Since you have no differentiation on if the value has been converted or not.

Do you see my point?

**Comment by davidkalosi** [comment]
Yeah your point is definitely valid. 
What about enforcing the constructor to accept only integers and create a factory method like 
```
Money.fromDecimal()
```

or something similar ?

**Comment by Snorlock** [comment]
I think that would be a better way of going about it. Atleast keep it out of the constructor and saying that you only work with raw integers.

We are ourselves forcing integer from the api, since we saw the need. Unfortunatly I will not have time to have a look at this since we are now past that point.

**Comment by davidkalosi** [comment]
I'll incorporate this into the next release together with your PR + update the docs accordingly.

**Comment by Snorlock** [comment]
Cool :+1:

**Comment by davidkalosi** [comment]
So this is what I came up with to make the library somewhat consistent

the constructor only accepts 2 parameters - an integer as amount and a string/object as currency.
The constructors now throws a ```TypeError``` when the amount is not an integer.
```
new Money(1000, 'EUR');
new Money(1000, Money.EUR);
```

2 factory methods were added - fromInteger and fromDecimal. both accept either 2 parameters as the constructor or an object with amount and currency fields

```
Money.fromDecimal(10.50, 'EUR');
Money.fromDecimal({amount: 10.50, currency: 'EUR'});

Money.fromInteger (1050, 'EUR');
Money.fromInteger ({amount: 1050, currency: 'EUR'});
```

what do you think of this solution ?

**Comment by Snorlock** [comment]
This seems like a good idea. Keeps it consistent.
How about on the way out? Let the user handle this maybe?

**Comment by davidkalosi** [comment]
exactly. once created internally money will be always integer. any formatting/displaying should be IMO done by the user since the requirements may vary from project to project.

**Comment by Snorlock** [comment]
:+1:

**Comment by davidkalosi** [comment]
I believe we have sorted it out, release 0.5 was merged yesterday with updated docs. Things should be pretty straight forward now.
