### ISSUE TITLE
What about toDecimal?

### ISSUE THREAD

**Issue by Ianfeather** [davidkalosi/js-money#6]
I'm implementing this for the first time so perhaps this is something obvious but if I want to eventually output the money as a decimal is this not something which should live within the money object code? 

Seems odd that you would safely be able to do calculations whilst it is represented as cents but then you risk causing an issue by having to do the toDecimal implementation yourself.

Thanks in advance for any advice

**Comment by caccialdo** [comment]
I tried to extend the class in https://github.com/davidkalosi/js-money/pull/7. You should check it out.

**Comment by drewclauson** [comment]
I wasn't ready to trust the math calculation of this:
```
return (this.amount / 100).toFixed(2);
```

So, since I'm only converting to decimal in order to display data, I'm doing a string manipulation to avoid any possibility of conversion issues (I think I had one scenario where this had actually happened, so I decided to stick with string operations)

```
function moneyToDecimalString(amount, currency) {
    amount = amount.toString();
    let position = amount.length - Money[currency].decimal_digits;
    return [amount.slice(0, position), '.', amount.slice(position)].join('');
}
```

Just FYI if it's helpful for you.  I have no idea which is better performance.  My code hasn't been upgraded to work with #7

**Comment by caccialdo** [comment]
Even outside of performance considerations, your method the currency's `decimal_digits` prop into account which definitely an issue in my pull request :disappointed:

Your implementation is definitely safe calculation-wise so I might use yours but I've failed to find an example where `.toFixed` falls short.

**Comment by caccialdo** [comment]
```
> 1-0.32
> 0.6799999999999999

> (1-0.32).toFixed(2)
> "0.68"

> 1-0.18
> 0.8200000000000001

> (1-0.18).toFixed(2)
> "0.82"
```

toFixed seems to be rounding to the closest decimal which I think is fine. If we really need to floor the value, we could use `.toFixed(n+1).slice(0, -1)`.

**Comment by drewclauson** [comment]
Now that I think about it, I think it was my backend API that was having the calculation failure and not Javascript... But even so I wanted to take the decimal_digits into account and this was the only way I could think of doing that, although this would use toFixed(2) and get the decimal in the right place.

```
return (this.amount / Math.pow(10, this.currency.decimal_digits)).toFixed(2);
```

**Comment by drewclauson** [comment]
Edit, missed the toFixed parameter change
```
return (this.amount / Math.pow(10, this.currency.decimal_digits)).toFixed(this.currency.decimal_digits);
```

**Comment by caccialdo** [comment]
Thanks for the help. I updated the `toString` and `toDecimal` method in https://github.com/davidkalosi/js-money/pull/7/files :+1:

**Comment by caccialdo** [comment]
https://github.com/davidkalosi/js-money/pull/7 was merged and version `v0.5.0` contains the method on its prototype.

**Comment by Ianfeather** [comment]
Thanks @caccialdo, you're my hero!

**Comment by Ianfeather** [comment]
New changes are looking great btw. Thanks all
